<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>E:\SteamLibrary\steamapps\common\OrbitalCrash\BepInEx\interop\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
